achat/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('achat.views',
                       url(r'^details$', 'cart_details', name='cart_details'),
                       url(r'^paiement$', 'paiement', name='paiement'),
                       url(r'^ipn$', 'ipn', name='ipn'),
                       url(r'^confirmation$', 'retour_paiement', name='confirmation'),
                       url(r'^annulation$', 'retour_annulation', name='annulation'),
                       )

kooblit/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^(?P<alt>\d{1})/$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^search/', include('search_engine.urls', namespace='search_engine')),
                       url(r'^accounts/', include('usr_management.urls', namespace='usr_management')),
                       url(r'^users/(?P<username>.{,30})/$', 'usr_management.views.user_profil', name='users'),
                       url(r'^book/', include('manage_books_synth.urls', namespace='book_management')),
                       url(r'^cart/', include('achat.urls', namespace='achat')),
                       )
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

usr_management/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^dashboard/$', 'usr_management.views.user_dashboard', name='dashboard'),
                       url(r'^login/$', 'usr_management.views.contact', name='login'),
                       url(r'^logout$', 'usr_management.views.user_logout', name='logout'),
                       url(r'^delete$', 'usr_management.views.user_suppression', name='delete'),
                       url(r'^confirmation/(?P<verification_id>[0-9a-f]{64})$', 'usr_management.views.email_confirm', name='email_confirm'),
                       url(r'^InputValidator$', 'usr_management.views.check_exist', name='validator'),
                       url(r'^renvoi/$', 'usr_management.views.resend_verification', name='resend_verification'),
                       url(r'^reinitialisation/$', 'usr_management.views.ask_reinitialisation', name='ask_reinitialisation'),
                       url(r'^reinit/(?P<r_id>[0-9a-f]{40})$', 'usr_management.views.do_reinitialisation', name='do_reinitialisation'),
                       url(r'^lire/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.lire_synthese', name='lire_synthese'),
                       url(r'^ajouter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.ajouter_synthese_gratuite', name='ajouter_synthese_gratuite'),
                       url(r'^noter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.noter_synthese', name='noter'),
                       url(r'^telecharger/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.download_pdf', name='download_pdf'),
                       )

templates/syntheses/one_synth.html
{% load staticfiles %}
{% load synth_tags %}
<div class="repre_image col-lg-2 col-md-3 col-sm-6 col-xs-12 {% if forloop.counter0|divisibleby:5 %}col-lg-offset-1{% endif %}" style="{% if forloop.counter0 >= 5  %}display:none;{% endif %}">
  <!-- <img src="{{img_url}}" /> -->
  <div class="image_extract" style="background:{{synth.style.background_color}};">
    {% if synth in syntheses_achetees %}
    <a href="{% url 'usr_management:lire_synthese' synth.id %}" class="etiquette_link" >
    {% else %}
    <a href="javascript:void(0)" class="etiquette_link" data-toggle="modal" data-target="#myModal_{{forloop.counter0}}">
    {% endif %}
    <img src="{{synth.style.logo.url}}" alt="Logo Kooblit" />
    <p class="koob_de">Koob de</p>
    <p class="title_extract">{{synth.book_title|title|slice:":88"}}{% if synth.book_title|length > 88 %}...{% endif %}</p></a>
    <a href="{% url 'users' synth.user.username %}"><p class="par">Par <span class="author_name">{{synth.user.username|title}}</span> </a> </p>
  </div>
  

  <div class="result_info_etiquette">
    <div class="stars">
      <div class="current_note stars_yellow" style="width:{% widthratio synth.note_moyenne 5 100 %}%;"></div>
      {% if synth in syntheses_a_noter %}
      <a class="note_link" href="javascript:void(0)" action="{% url 'usr_management:noter' synth.id %}" note=5><div class="vote vote_note_5 stars_yellow" style="width:150px;"></div></a>
      <a class="note_link" href="javascript:void(0)" action="{% url 'usr_management:noter' synth.id %}" note=4><div class="vote vote_note_4 stars_yellow" style="width:120px;"></div></a>
      <a class="note_link" href="javascript:void(0)" action="{% url 'usr_management:noter' synth.id %}" note=3><div class="vote vote_note_3 stars_yellow" style="width:90px;"></div></a>
      <a class="note_link" href="javascript:void(0)" action="{% url 'usr_management:noter' synth.id %}" note=2><div class="vote vote_note_2 stars_yellow" style="width:60px;"></div></a>
      <a class="note_link" href="javascript:void(0)" action="{% url 'usr_management:noter' synth.id %}" note=1><div class="vote vote_note_1 stars_yellow" style="width:30px;"></div></a>
      {% endif %}
    </div>

    <div class="result_description">
      <p class="misc_info_text misc_info col-xs-6">{{synth.nbre_notes}} notes</p>
      <p class="misc_info_text misc_info col-xs-6" style="text-align:right;"><b>{{synth.nb_pages}}</b> page{{synth.nb_pages|pluralize}}</p>
      <p class="misc_info_text misc_info col-xs-12" style="text-align: center;">Publié le {{synth.date|date:"d/m/Y"}}</p>
      <div class="col-xs-12 misc_info boutons_prix">
      {% if synth in syntheses_achetees %}
        <p class="col-xs-12" style="padding: 0px;">
          <a href="{% url 'usr_management:lire_synthese' synth.id %}" class="abtn see_extract" >
            Lire la synthèse
          </a>
        </p>
      {% elif synth.is_free %}
        <p class="col-xs-12" style="padding: 0px;">
          <a href="javascript:void(0)" class="btn_desc abtn see_extract" data-toggle="modal" data-target="#myModal_{{forloop.counter0}}">
            Voir un extrait
          </a>
        </p>
        <p class="misc_info free_price col-4 col-xs-4">0,0€</p>
        <p class="col-7 col-offset-1 col-xs-7 col-xs-offset-1" style="padding:1px;">
          <a href="{% url 'usr_management:ajouter_synthese_gratuite' synth.id %}" class="btn_call btn_desc abtn buy_resume">
            Lire gratuitement
          </a>
        </p>
      {% else %}
        <p class="col-xs-12" style="padding: 0px;">
          <a href="javascript:void(0)" class="btn_desc abtn see_extract" data-toggle="modal" data-target="#myModal_{{forloop.counter0}}">
            Voir un extrait
          </a>
        </p>
        <p class="misc_info price col-4 col-xs-4">{{synth.prix}}€</p>
        <p class="col-7 col-offset-1 col-xs-7 col-xs-offset-1" style="padding:1px;">
          <button href="javascript:void(0)" class="btn_important btn_desc abtn buy_resume" form="form_ajout_{{synth.id}}">
            Ajouter au panier
          </button>
        </p>
        <form id="form_ajout_{{synth.id}}" method="POST" >{% csrf_token %}
          <input type="hidden" name="synthese" value="{{synth.id}}">
        </form>
      {% endif %}
      </div>
    </div> <!-- result_description -->
  </div> <!-- result_infos_etiquette -->
</div> <!-- repre_image -->

{% if not synth in syntheses_achetees %}
<!-- Modal -->
<div class="modal fade" id="myModal_{{forloop.counter0}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>

        <h4 class="modal-title" id="myModalLabel">
          <img src="{% static 'img/logo/little_owl_grey.png' %}" width="50px" alt="logo kooblit" />
          {{synth.book_title}}
        </h4>
      </div>

      <div class="modal-body">
        {{synth.extrait|safe}}
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div> <!-- Modal -->
{% endif %}

templates/syntheses/syntheses_rows.html
{% if syntheses %}


  
  <div class="row list_extract">
    {% if user.is_authenticated %}
      {% with syntheses_achetees=user.userkooblit.get_syntheses_achetees_ou_ecrites  syntheses_a_noter=user.userkooblit.get_syntheses_a_noter %}
        {% for synth in syntheses %}
          {% if forloop.counter0|divisibleby:5 %}
          <div class="row row_syntheses">
          {% endif %}
          {% include "syntheses/one_synth.html" with synth=synth syntheses_achetees=syntheses_achetees syntheses_a_noter=syntheses_a_noter %}
          {% if forloop.last or forloop.counter0|add:1|divisibleby:5 %}
          </div>
          {% endif %}
        {% endfor %}
      {% endwith %}
    {% else %}
      {% for synth in syntheses %}
        {% if forloop.counter0|divisibleby:5 %}
        <div class="row row_syntheses">
        {% endif %}
        {% include "syntheses/one_synth.html" with synth=synth syntheses_achetees="" syntheses_a_noter="" %}
        {% if forloop.last or forloop.counter0|add:1|divisibleby:5 %}
        </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div> 
  {% if syntheses|length > 5 and do_plus %}
   <div class="row">
    <div class="col-xs-offset-10 col-xs-1">
      <button type="button" class="plus_button" onclick='afficher_plus()'>Plus</button>
    </div> <!-- Bouton PLUS -->
  </div>
  {% endif %}

{% else %}
  <h1 class="no_synthese">{{message}}</h1>
{% endif %}