achat/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('achat.views',
                       url(r'^details$', 'cart_details', name='cart_details'),
                       url(r'^paiement$', 'paiement', name='paiement'),
                       url(r'^ipn$', 'ipn', name='ipn'),
                       url(r'^confirmation$', 'retour_paiement', name='confirmation'),
                       url(r'^annulation$', 'retour_annulation', name='annulation'),
                       )

kooblit/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^(?P<alt>\d{1})/$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^search/', include('search_engine.urls', namespace='search_engine')),
                       url(r'^accounts/', include('usr_management.urls', namespace='usr_management')),
                       url(r'^users/(?P<username>.{,30})/$', 'usr_management.views.user_profil', name='users'),
                       url(r'^book/', include('manage_books_synth.urls', namespace='book_management')),
                       url(r'^cart/', include('achat.urls', namespace='achat')),
                       )
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

search_engine/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'search_engine.search_views.search_view', name='search'),
    url(r'^complete/$', 'search_engine.search_views.search_between', name='search_between')
)

usr_management/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^dashboard/$', 'usr_management.views.user_dashboard', name='dashboard'),
                       url(r'^login/$', 'usr_management.views.contact', name='login'),
                       url(r'^logout$', 'usr_management.views.user_logout', name='logout'),
                       url(r'^delete$', 'usr_management.views.user_suppression', name='delete'),
                       url(r'^confirmation/(?P<verification_id>[0-9a-f]{64})$', 'usr_management.views.email_confirm', name='email_confirm'),
                       url(r'^InputValidator$', 'usr_management.views.check_exist', name='validator'),
                       url(r'^renvoi/$', 'usr_management.views.resend_verification', name='resend_verification'),
                       url(r'^reinitialisation/$', 'usr_management.views.ask_reinitialisation', name='ask_reinitialisation'),
                       url(r'^reinit/(?P<r_id>[0-9a-f]{40})$', 'usr_management.views.do_reinitialisation', name='do_reinitialisation'),
                       url(r'^lire/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.lire_synthese', name='lire_synthese'),
                       url(r'^ajouter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.ajouter_synthese_gratuite', name='ajouter_synthese_gratuite'),
                       url(r'^noter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.noter_synthese', name='noter'),
                       url(r'^telecharger/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.download_pdf', name='download_pdf'),
                       )

templates/navigation/base.html
{% load static %}

<nav class="nav-bar-kooblit navbar navbar-fixed-top navbar-default " role="navigation">
  <div class="container">

    <div class="navbar-header">
      {% if not dont_collapse %}
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      {% endif %}
      {% block nav_header %}{% endblock %}
    </div>

    <div {% if not dont_collapse %}class="collapse navbar-collapse"{% endif %}>
      {% block nav_search %}{% endblock %}

      <ul class="nav navbar-nav navbar-right">

        {% block nav_cart %}
          {% if request.nbre_achats %}
            <li class="icon_navbar">
              <a href="{% url 'achat:cart_details' %}" class="dropdown-toggle">

                <img class="icon_navbar" src="{% static 'img/ico/Cart.png'%}" class="navbar_img" />
                <span class="nb_achats">{{ request.nbre_achats }}</span>

              </a>
            </li>
          {% endif %}
        {% endblock %}

        {% block nav_profile %}
          <li  class="icon_navbar dropdown">
            <a id="home_profil" href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
              <img class="icon_navbar" alt="" src="{% static "img/ico/Home.png" %}">
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="{% url 'usr_management:dashboard' %}"><i class="fa fa-user"></i> Mon profil </a>
              </li>

              <li class="divider"></li>

              <li>
                <a href="{% url 'usr_management:logout' %}"><i class="fa fa-key"></i> Se déconnecter</a>
              </li>
            </ul>
          </li>
        {% endblock %}

      </ul>
    </div>
  </div>
</nav>

templates/navigation/fixed_base.html
{% load static %}

<nav class="nav-bar-kooblit navbar navbar-default " role="navigation">
  <div class="container">

    <div class="navbar-header">
      {% if not dont_collapse %}
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      {% endif %}
      {% block nav_header %}{% endblock %}
    </div>

    <div {% if not dont_collapse %}class="collapse navbar-collapse"{% endif %}>
      {% block nav_search %}{% endblock %}

      <ul class="nav navbar-nav navbar-right">

        {% block nav_cart %}
          {% if request.nbre_achats %}
            <li class="icon_navbar">
              <a href="{% url 'achat:cart_details' %}" class="dropdown-toggle">

                <img class="icon_navbar" src="{% static 'img/ico/Cart.png'%}" class="navbar_img" />
                <span class="nb_achats">{{ request.nbre_achats }}</span>

              </a>
            </li>
          {% endif %}
        {% endblock %}

        {% block nav_profile %}
          <li  class="icon_navbar dropdown">
            <a id="home_profil" href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
              <img class="icon_navbar" alt="" src="{% static "img/ico/Home.png" %}">
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="{% url 'usr_management:dashboard' %}"><i class="fa fa-user"></i> Mon profil </a>
              </li>

              <li class="divider"></li>

              <li>
                <a href="{% url 'usr_management:logout' %}"><i class="fa fa-key"></i> Se déconnecter </a>
              </li>
            </ul>
          </li>
        {% endblock %}

      </ul>
    </div>
  </div>
</nav>

templates/navigation/inscription.html
{% extends "navigation/base.html" %}
{% load staticfiles %}

{% block nav_search %}
  <form id="search_form" class="collapse navbar-collapse navbar-form navbar-left" action="{% url 'search_engine:search' %}" role="search" method="get" onsubmit="return display_loader('#ajax_loader')" >
    <div class="form-group">
      <div class="dropdown">
        <input id="search_bar" type="text" class="form-control " placeholder="Rechercher un ouvrage..." name='title'>
        <img src="{% static "img/ajax-loader.gif"%}" id="ajax_loader" />
      </div>
    </div>
    <button type="submit" style="position:absolute;top:-9999px;width:1px;" ></button>
  </form>
{% endblock %}

{% block nav_header %}
  <ul class="navbar-nav">
    <li>
      <a class="navbar-brand" href="{% url 'homepage'%}">
       <img id="point_kooblit" src="{% static "img/logo/little_baniere_kooblit.png" %}" alt="Logo Kooblit" />
      </a>
    </li>
  </ul>
{% endblock %}


{% block nav_profile %}
{% endblock %}

templates/navigation/main.html
{% extends "navigation/base.html" %}
{% load staticfiles %}

{% block nav_search %}
  <form id="search_form" class="collapse navbar-collapse navbar-form navbar-left" action="{% url 'search_engine:search' %}" role="search" method="get" onsubmit="return display_loader('#ajax_loader')" >
    <div class="form-group">
      <div class="dropdown">
        <input id="search_bar" type="text" class="form-control " placeholder="Rechercher un ouvrage..." name='title'>
        <img src="{% static "img/ajax-loader.gif"%}" id="ajax_loader" />
      </div>
    </div>
    <button type="submit" style="position:absolute;top:-9999px;width:1px;" ></button>
  </form>
{% endblock %}

{% block nav_header %}
  <ul class="navbar-nav">
    <li>
      <a class="navbar-brand" href="{% url 'homepage'%}">
       <img id="point_kooblit" src="{% static "img/logo/little_baniere_kooblit.png" %}" alt="Logo Kooblit" />
      </a>
    </li>
  </ul>
{% endblock %}

{% block nav_profile %}
  {% if user.is_authenticated %}
    {{ block.super }}
  {% else %}
    <li>
      <a href="{% url 'usr_management:login' %}#enregistrement" class="navbar_login"> S'enregistrer</a>
    </li>
    <li>
      <a href="{% url 'usr_management:login' %}#connection" class="navbar_login"> Se connecter</a>
    </li>
  {% endif %}
{% endblock %}

templates/navigation/main_without_search.html
{% extends "navigation/fixed_base.html" %}
{% load staticfiles %}

{% block nav_search %}
{% endblock %}

{% block nav_header %}
  <ul class="navbar-nav">
    <li>
      <a class="navbar-brand" href="{% url 'homepage'%}">
       <img id="point_kooblit" src="{% static "img/logo/little_baniere_kooblit.png" %}" alt="Logo Kooblit" />
      </a>
    </li>
  </ul>
{% endblock %}

{% block nav_profile %}
  {% if user.is_authenticated %}
    {{ block.super }}
  {% else %}
    <li>
      <a href="{% url 'usr_management:login' %}#enregistrement" class="navbar_login"> S'enregistrer</a>
    </li>
    <li>
      <a href="{% url 'usr_management:login' %}#connection" class="navbar_login"> Se connecter</a>
    </li>
  {% endif %}
{% endblock %}

templates/navigation/nav_lecture.html
{% extends "navigation/base.html" %}
{% load staticfiles %}

{% block nav_search %}
{% endblock %}

{% block nav_header %}
  <ul class="navbar-nav">
    <li>
      <a class="navbar-brand" href="{% url 'homepage'%}">
       <img id="point_kooblit" src="{% static "img/logo/little_baniere_kooblit.png" %}" alt="Logo Kooblit" />
      </a>
    </li>
  </ul>
{% endblock %}

{% block nav_profile %}
  {% if user.is_authenticated %}
    {{ block.super }}
  {% else %}
    <li>
      <a href="{% url 'usr_management:login' %}#enregistrement" class="navbar_login"> S'enregistrer</a>
    </li>
    <li>
      <a href="{% url 'usr_management:login' %}#connection" class="navbar_login"> Se connecter</a>
    </li>
  {% endif %}
{% endblock %}

templates/navigation/search_less.html
{% extends "navigation/base.html" %}
{% load static %}

{% block nav_header %}
  <ul class="navbar-nav">
    <li>
      <span class="navbar-brand" >
       <img id="point_kooblit" src="{% static "img/logo/little_baniere_kooblit.png" %}" alt="Logo Kooblit" />
      </span>
    </li>
  </ul>
{% endblock %}

{% block nav_profile %}
  {% if user.is_authenticated %}
    {{ block.super }}
  {% else %}
    <li>
      <a href="{% url 'usr_management:login' %}#enregistrement" class="navbar_login navbar_inscription"> S'inscrire</a>
    </li>
    <li>
      <a href="{% url 'usr_management:login' %}#connection" class="navbar_login"> Se connecter</a>
    </li>
  {% endif %}
{% endblock %}

templates/navigation/titled.html
{% extends "navigation/base.html" %}
{% load staticfiles %}

{% block nav_header %}
  <h2 class="header_title">Kooblit de <span class="book_title">{{title}}</span> par {{author}}</h2>
{% endblock %}