achat/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('achat.views',
                       url(r'^details$', 'cart_details', name='cart_details'),
                       url(r'^paiement$', 'paiement', name='paiement'),
                       url(r'^ipn$', 'ipn', name='ipn'),
                       url(r'^confirmation$', 'retour_paiement', name='confirmation'),
                       url(r'^annulation$', 'retour_annulation', name='annulation'),
                       )

kooblit/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^(?P<alt>\d{1})/$', 'kooblit.views.homepage', name='homepage'),
                       url(r'^search/', include('search_engine.urls', namespace='search_engine')),
                       url(r'^accounts/', include('usr_management.urls', namespace='usr_management')),
                       url(r'^users/(?P<username>.{,30})/$', 'usr_management.views.user_profil', name='users'),
                       url(r'^book/', include('manage_books_synth.urls', namespace='book_management')),
                       url(r'^cart/', include('achat.urls', namespace='achat')),
                       )
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

manage_books_synth/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       url(r'^(?P<book_title>.{1,' + str(settings.MAX_BOOK_TITLE_LEN) + '})/post/', 'manage_books_synth.views.upload_medium', name='post_medium'),
                       url(r'^(?P<book_title>.{1,' + str(settings.MAX_BOOK_TITLE_LEN) + '})/ask/$', 'manage_books_synth.views.demande_livre', name='ask'),
                       url(r'^(?P<book_title>.{1,' + str(settings.MAX_BOOK_TITLE_LEN) + '})/details$', 'manage_books_synth.views.selection', name='selection'),
                       url(r'^(?P<book_title>.{1,' + str(settings.MAX_BOOK_TITLE_LEN) + '})/$', 'manage_books_synth.views.book_detail', name='details'),
                       )

search_engine/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^$', 'search_engine.search_views.search_view', name='search'),
    url(r'^complete/$', 'search_engine.search_views.search_between', name='search_between')
)

usr_management/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^dashboard/$', 'usr_management.views.user_dashboard', name='dashboard'),
                       url(r'^login/$', 'usr_management.views.contact', name='login'),
                       url(r'^logout$', 'usr_management.views.user_logout', name='logout'),
                       url(r'^delete$', 'usr_management.views.user_suppression', name='delete'),
                       url(r'^confirmation/(?P<verification_id>[0-9a-f]{64})$', 'usr_management.views.email_confirm', name='email_confirm'),
                       url(r'^InputValidator$', 'usr_management.views.check_exist', name='validator'),
                       url(r'^renvoi/$', 'usr_management.views.resend_verification', name='resend_verification'),
                       url(r'^reinitialisation/$', 'usr_management.views.ask_reinitialisation', name='ask_reinitialisation'),
                       url(r'^reinit/(?P<r_id>[0-9a-f]{40})$', 'usr_management.views.do_reinitialisation', name='do_reinitialisation'),
                       url(r'^lire/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.lire_synthese', name='lire_synthese'),
                       url(r'^ajouter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.ajouter_synthese_gratuite', name='ajouter_synthese_gratuite'),
                       url(r'^noter/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.noter_synthese', name='noter'),
                       url(r'^telecharger/(?P<synthese_id>[0-9a-f]{1,64})$', 'usr_management.views.download_pdf', name='download_pdf'),
                       )

templates/base.html
{% extends "main_base.html" %}

{% block navigation %}
  {% include 'navigation/main.html' %}
{% endblock %}

templates/details.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/selection.css"%}">
    <link rel="stylesheet" href="{% static "css/details.css"%}">
{% endblock %}

{% block content %}
{% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="alert alert-dismissable {% if message.tags %} alert-{{ message.tags }} {% endif %}">
          <button type="button" class="close" data-dismiss="alert">×</button>
          {{ message|safe }}
        </div>
      {% endfor %}
    </div>
{% endif %}

<div class="container">
    <div class="selection_header">
      <h2>Synthèses disponibles pour le livre</h2>
      <h3>{{title|title}}</h3>
  </div>
</div>

<div class="container" style="padding-left:0px;">
  <div class="col-sm-2 col-sm-offset-0 col-xs-10 col-xs-offset-1">

    <div class="row">
      <div class="repre_image col-xs-12">
        <a title="Acheter le livre" href="{{buy_url}}" target="_blank">
          <img src="{{img_url}}" />
        </a>
        <div class="result_info">
          <div class="result_title">
            {{title|title}}
          </div>
          <div class="result_author">
            {{author}}
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="bs-component col-xs-12">
        <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Acheter le livre" href="{{buy_url}}" target="_blank">
          <img src="{% static "img/pictos/Credit_card.png" %}" />
          <div style="display:inline-block;line-height: 1.5em;height: 3em; width: 105px; vertical-align: middle;"> Acheter le livre </div>
        </a>
      </div>

      <div class="bs-component col-xs-12">
        <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Je vends une synthèse" href="{% url 'book_management:post_medium' title %}">
          <img src="{% static "img/pictos/Sell.png" %}" />
          <div style="display:inline-block;line-height: 1.5em;height: 3em; width: 105px; vertical-align: middle;">Vendre une synthèse</div>
        </a>
      </div>
    </div>

  </div>

  <div class="col-sm-offset-1 col-sm-9 col-xs-12">
  {% include 'syntheses/syntheses_rows.html' with syntheses=syntheses do_plus=True message="Désolé, il n'y a aucune synthèse disponible pour ce livre" %}
  </div>

</div>
{% endblock %}

{% block script_block %}
<script src="{% static "js/colorize.js" %}" type="text/javascript"></script>
<script src="{% static "js/handle_note.js" %}" type="text/javascript"></script>
<script type="text/javascript">
  $(window).load(function(){
      $(".image_extract").each(function(index, element){
        colorize(index, element);
      })
  });
</script>
<script type="text/javascript">

$('.bs-component [data-toggle="tooltip"]').tooltip();
$(function () {
  $(".note_link").click(send_note);
  $(".vote").hover(function(){
    $(this).parent().parent().find(".current_note").addClass("current_note_hidden");
  },
  function () {
    $(this).parent().parent().find(".current_note").removeClass("current_note_hidden");
  });
})
function afficher_plus(){
  $('.repre_image').each(function(){
    var res = $(this);
    res.css('display','inline-block');
  });
  $('.plus_button').css('display','none');
}

</script>
{% endblock %}

templates/edition_synthese.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/medium-editor.css"%}">
    <link rel="stylesheet" href="{% static "css/themes/default.css"%}">
    <link rel="stylesheet" href="{% static "css/edition.css"%}">
{% endblock %}

{% block content %}
    <form method="POST" id="form_synth">{% csrf_token %}
        <input id="container" name='q' type="hidden" value=""></input>
    </form>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="message_container">
                    <div id="enregistrement-en-cours" class="alert alert-dismissable alert-success" style="display:none;">
                      Enregistrement de votre fichier.
                    </div>

                    <div id="enregistrement-success" class="alert alert-dismissable alert-success" style="display:none;">
                      Votre fichier a bien été enregistré.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container editeur">
        <div class="row">
          <div class="repre_image">
            <a title="Acheter le livre" target="_blank" href="{{u_b.buy_url}}">
                <img src="{% if u_b.medium_image != None %}{{u_b.medium_image}}{% else %}{{u_b.image}}{% endif %}">
            </a>
          </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h2 class="titre_synth">Koob de <span class="edition_bold" >{{book.title}}</span> par <span class="edition_bold">{{username}}</span></h2>
                <!-- <div class="titre"></div> -->
                <div id="cadre_edition" class="editable">{{content|safe}}</div>
                <div class="last_row">
                    <button class="btn_call_sec button-sauvegarder" onclick="sauvegarder()"> Sauvegarder </button>
                    <button type="submit" value="quit" name="_quit" class="btn_call_sec " onclick="envoyer()" form="form_synth" > Sauvegarder &amp; quitter </button>
                    <button  value="publish" name="_publish" class="btn_important " onclick="choix_prix('_publish')" > Publier </button>
                </div>
            </div>
        </div>
    </div> <!-- editeur -->
    <div class="container choix_prix hidden">
        <h2>A quel prix souhaitez-vous vendre votre synthèse?</h2>
        Minimum 2€, pas de maximum, mais attention, un prix trop élevé limitera les téléchargements.

        <p><input name="prix" class="price_selector" type="number" min="2" step=0.1 placeholder="{% if synthese %}{{synthese.prix}}{% else %}0,00{% endif %}" value="{% if synthese %}{{synthese.prix}}{% else %}0,00{% endif %}" form="form_synth" />€</p>
        <p><ul id="error_prix"></ul></p>
        <a href="#"><button value="retour" name="retour" class="btn_call_sec" onclick="retour()" > <i class="fa fa-arrow-circle-o-left"></i> Retour </button></a>

        <button class="btn_important" type="submit" value="publish" name="_publish" onclick="envoyer()" form="form_synth"> Valider </button>
    </div>
{% endblock %}

{% block script_block %}
    <script src="{% static "js/medium-editor.js"%}"></script>

    <script>
    $(function(){
        if($('#cadre_edition').html() ===""){
            $('#cadre_edition').html("<br/>");
        }
    });
        var changed = 0;
        var editor = new MediumEditor('.editable', {
            buttonLabels: 'fontawesome'
        });
        var d = new Date();
        var t_interval = d.getTime();
        var t_editor = d.getTime();

        $('.editable').on('input', function() {
            var d = new Date();
            t_editor = d.getTime();
            changed = 1;
        });
        function retour(){
            $('.editeur').removeClass('hidden');
            $('.choix_prix').addClass('hidden');
        }
        function choix_prix(nom) {
            $('.button-prix').attr('name', nom);
            $('.editeur').addClass('hidden');
            $('.choix_prix').removeClass('hidden');
            $('.price_selector').focus();
        }
        function sauvegarder () {
            var ser = editor.serialize();
            $.ajax({
                    url: "{% url 'book_management:post_medium' book.title %}",
                    type: "POST",
                    cache: false,
                    success: function (data) {
                        $("#enregistrement-en-cours").css('display','none');
                        $("#enregistrement-success").fadeIn();
                        setTimeout(function() {$("#enregistrement-success").fadeOut();},2000);
                    },
                    beforeSend: function(){
                        $("#enregistrement-en-cours").fadeIn();
                        changed = 0;
                        return true;
                    }
                    ,
                    data: {
                    q: ser['cadre_edition']['value'],
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]')[0].value
                    }
            });
        }
        function envoyer () {
            var ser = editor.serialize();
            $('input[name="q"]')[0].value = ser['cadre_edition']['value'];
        }
        var timer = setInterval(function() {
            var d = new Date();
            t_interval = d.getTime();
            if(t_interval - t_editor >= 2000 && changed){
                var ser = editor.serialize();
                $.ajax({
                        url: "{% url 'book_management:post_medium' book.title %}",
                        type: "POST",
                        cache: false,
                        success: function (data) {
                            $("#enregistrement-en-cours").css('display','none');
                            $("#enregistrement-success").fadeIn();
                            setTimeout(function() {$("#enregistrement-success").fadeOut();},5000);
                        },
                        data: {
                            q:ser['cadre_edition']['value'],
                            csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]')[0].value
                        }
                });
                changed = 0;
            }
        }, 2000);
    </script>
{% endblock %}

templates/email_reinitialisation.html
<h1> Hello {{ username }} <h1>
<p>Vous avez demandé la réinitialisation de votre mot de passe<p><br/>
	Clickez sur le lien suivant pour changer votre mot de passe.<br/>
{{base_url}}{% url 'usr_management:do_reinitialisation' validation_id %}

templates/lecture.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %}
  <link href="{% static "css/lecture.css" %}" rel="stylesheet">
{% endblock %}


{% block navigation %}
  {% include 'navigation/main_without_search.html' %}
{% endblock %}

{% block content %}
  <div class="row row_image_couv">
    <div class="repre_image">
      <a title="Acheter le livre" target="_blank" href="{{u_b.buy_url}}">
          <img src="{% if u_b.medium_image != None %}{{u_b.medium_image}}{% else %}{{u_b.image}}{% endif %}">
      </a>
    </div>
    <div class="bs-component">
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Acheter le livre" href="{{u_b.buy_url}}" target="_blank">
        <img src="{% static "img/pictos/Credit_card.png" %}" />
        Acheter le livre
      </a>
    </div>
  </div>
  {% if messages %}
    <div class="container" >
      {% for message in messages %}
        <div class="alert alert-dismissable {% if message.tags %} alert-{{ message.tags }} {% endif %}">
          <button type="button" class="close" data-dismiss="alert">×</button>
          {{ message|safe }}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <h2 class="titre_synth">Koob de <span class="edition_bold" >{{book.title}}</span> par <span class="edition_bold">{{synth.user.username}}</span></h2>
  {% for page in synth.pages %}
  <div id="page_{{forloop.counter}}" class="container resume  {% if forloop.counter > 1 %} hidden {% endif %}" style="margin-bottom: 50px;">
    <div class="row">
      <div class="col-xs-12 col-xs-offset-0 col-md-10 col-md-offset-1">
      {{ page|safe }}
      </div>
    </div>
  </div>
  {% endfor %}

{% endblock %}
{% block footer %}
  {% if synth.pages|length > 1%}

  {% endif %}
  <footer >
  <nav class="navbar navbar-default" role="navigation" style="background:none;">
  <div class="container-fluid" style="background:none;">
    <div class="navbar-header" style="background:none;">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_footer">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="nav_footer" style="background:none;">
    <a class="footer_link" href="#top" >
      <button class="btn" >
        Aller en haut <i class="fa fa-arrow-circle-o-up"></i>
      </button>
    </a>
    <!--
    <ul class="pagination" >
      <li id="back_link" class="disabled"><a href="javascript:void(0)" onclick="change_page('back')">«</a></li>
      {% for page in synth.pages %}
      <li id="page_{{forloop.counter}}_link" class=" {% if forloop.counter == 1 %} active {% endif %}"><a href="javascript:void(0)" onclick="change_page({{forloop.counter}})">{{forloop.counter}}</a></li>
      {% endfor %}
      <li id="next_link"><a href="javascript:void(0)" onclick="change_page('next')">»</a></li>
    </ul> -->
    <a class="footer_link" href="{% url 'usr_management:download_pdf' synth.id %}" ><button class="btn" ><i class="fa fa-file-pdf-o"> </i>&nbsp;Télécharger pdf </button></a>
    </div>
  </nav>
  </footer>
{% endblock %}
{% block script_block %}
<script type="text/javascript">
window.data = {"current_page":1, "total_pages":{{synth.pages|length}}, "has_plus":false};
$(function(){
  if(window.data["total_pages"] >= 4){
    for (var i = 4; i < window.data["total_pages"]; i++) {
      $("#page_"+String(i+1)+"_link").addClass("hidden");
    }
    $("#next_link").find("a").html("+");
    window["has_plus"] = true;
    $(".pagination").hover(function () {
      for (var i = 4; i < window.data["total_pages"]; i++) {
        $("#page_"+String(i+1)+"_link").removeClass("hidden");
      }
      $("#next_link").find("a").html("»");
    }, function(){
      for (var i = 4; i < window.data["total_pages"]; i++) {
        $("#page_"+String(i+1)+"_link").addClass("hidden");
      }
      $("#next_link").find("a").html("+");
    });
  }
});
function change_page(page_nber){
  if(page_nber === 'back' && window.data["current_page"] > 1){
    $("#page_"+ String(window.data["current_page"])).addClass('hidden');
    $("#page_"+ String(window.data["current_page"]) + "_link").removeClass('active');
    window.data["current_page"] --;
    $("#page_"+ String(window.data["current_page"])).removeClass('hidden');
    $("#page_"+ String(window.data["current_page"]) + "_link").addClass('active');
    if( window.data["current_page"] === 1){
      $("#back_link").addClass("disabled");
      $("#next_link").removeClass("disabled");
    }
  }
  else if(page_nber === 'next' && window.data["current_page"] < {{synth.pages|length}}){
    $("#page_"+ String(window.data["current_page"])).addClass('hidden');
    $("#page_"+ String(window.data["current_page"]) + "_link").removeClass('active');
    window.data["current_page"] ++;
    $("#page_"+ String(window.data["current_page"])).removeClass('hidden');
    $("#page_"+ String(window.data["current_page"]) + "_link").addClass('active');
    if( window.data["current_page"] === {{synth.pages|length}}){
      $("#next_link").addClass("disabled");
      $("#back_link").removeClass("disabled");
    }
  }
  else if(!isNaN(page_nber)) {
    if(page_nber >= 1 && page_nber <= {{synth.pages|length}} && window.data["current_page"] !== page_nber){
      $("#page_"+ String(window.data["current_page"])).addClass('hidden');
      $("#page_"+ String(window.data["current_page"]) + "_link").removeClass('active');
      window.data["current_page"] = page_nber;
      $("#page_"+ String(window.data["current_page"])).removeClass('hidden');
      $("#page_"+ String(window.data["current_page"]) + "_link").addClass('active');
      if( window.data["current_page"] === {{synth.pages|length}}){
        $("#next_link").addClass("disabled");
      }
      else{
        $("#next_link").removeClass("disabled");
      }
      if( window.data["current_page"] === 1){
        $("#back_link").addClass("disabled");
      }
      else{
        $("#back_link").removeClass("disabled");
      }
    } 
  }
  window.scrollTo(0,0);
}

// $(function () {
//   var lastScrollTop = $(window).scrollTop();
//   if ($("#block_content").height() > $(window).height()) {
//     $(window).scroll(function (data_event){
//       var st = $(this).scrollTop();
//       console.log(st)
//       console.log(lastScrollTop)
//       if (st > lastScrollTop){
//           if($(".to_top").css('display') === "none"){
//             $("footer").fadeOut("fast", function(){
//               $(".to_top").fadeIn("fast");
//             });
//           }
//       } else if (st < lastScrollTop){
//           if($("footer").css('display') === "none"){
//             console.log("in2");
//             $(".to_top").fadeOut("fast", function(){
//               $("footer").fadeIn("fast");
//             });
//           }
//           // if(st < lastScrollTop){
//           // }
//           // else {
//           //   $(".to_top").style('bottom', $("footer").height()); 
//           // }
//       }
//       lastScrollTop = st;
//     });
//   }
// });
  $(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
            || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
               if (target.length) {
                 $('html,body').animate({
                     scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});

</script>
{% endblock %}

templates/row_result.html
{% load static %}
{% if resultat %}
<div class="row result_line">
      {% for item in resultat %}

        {% if forloop.counter0|divisibleby:nb_result and forloop.counter0 %}
          </div><div class="row result_line">
        {% endif %}

        <div class="element img_container2 col-md-2 col-sm-4 col-xs-6" {% if forloop.counter0 >= nb_result  %}style=""{% endif %}>

            <div class="repre_image col-xs-12 col-sm-12 col-md-12">
              <a data-toggle="tooltip" data-placement="top" title="{{ item.title }}" data-original-title="Je cherche une synthèse" href="{% url 'book_management:search' item.title %}">
                {% if item.image %}
                    <img src="{{ item.image }}" />
                {% else %}
                    <img src='{% static 'img/empty_gallery.png' %}' />
                {% endif %}
              </a>
            </div>

            <div class="result_info col-xs-12 col-sm-12 col-md-12">
              <div class="result_title">
                {{item.little_title|title|safe}}
              </div>

              <div class="result_author">
                {{item.author}}
              </div>
            </div>

        </div>

      {% endfor %}
</div> <!-- row result_line -->
{% endif %}

templates/selection.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/selection.css"%}">
{% endblock %}

{% block content %}
{% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="alert alert-dismissable {% if message.tags %} alert-{{ message.tags }} {% endif %}">
          <button type="button" class="close" data-dismiss="alert">×</button>
          {{ message|safe }}
        </div>
      {% endfor %}
    </div>
{% endif %}

<div class="container">

  <div class="row">
    <div class="selection_header">
      <h2>Vous avez sélectionné</h1>
      <h3>{{title|title}}</h3>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-3 col-sm-offset-0 col-xs-10 col-xs-offset-1">
      <div class="repre_image">
        <a title="Acheter le livre" href="{{buy_url}}" target="_blank">
          <img src="{{img_url}}">
        </a>
      </div>

      <div class="result_info">
        <div class="result_title">
          {{title|title}}
        </div>

        <div class="result_author">
          {{author}}
        </div>
      </div>
    </div>

    <div class="col-sm-9">
      {% if description %}
        <div class="row">
          <div class="infos col-xs-12">
            <h3>Description</h3>
            <p>{{description|safe}}</p>
          </div>
        </div>
      {% endif %}

      <div class="row">
        <div class="infos col-xs-12">
          <h3>Informations</h3>
            <div class="row">
            {% if langue %}
              <p class="misc_info col-xs-6">Langue: {{langue}}</p>
            {% endif %}
            {% if genre %}
              <p class="misc_info col-xs-6">Genre: {{genre}}</p>
            {% endif %}
            {% if publication_date %}
              <p class="misc_info col-xs-6">Publié: {{publication_date}}</p>
            {% endif %}
            {% if nb_of_pages %}
              <p class="misc_info col-xs-6">Pages: {{nb_of_pages}}</p>
            {% endif %}

            <p class="misc_info col-xs-6">Syntheses disponibles: {{nb_syntheses}}</p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="bs-component col-xs-4">
          <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Acheter le livre" href="{{buy_url}}" target="_blank">
            <img src="{% static "img/pictos/Credit_card.png" %}" />
            <br />
            Acheter le livre
          </a>
        </div>
        <div class="bs-component col-xs-4">
          <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Je cherche une synthèse" href="{% url 'book_management:details' title %}">
            <img src="{% static "img/pictos/Search.png" %}" />
            <br />
            Voir les synthèses
          </a>
        </div>
        <div class="bs-component col-xs-4">
          <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Je vends une synthèse" href="{% url 'book_management:post_medium' title %}">
            <img src="{% static "img/pictos/Sell.png" %}" />
            <br />
            Vendre une synthèse
          </a>
        </div>
      </div>

    </div>
  </div>
</div>
{% if not nb_syntheses and add_modal %}
<!-- Modal -->
<div class="modal fade" id="myModal_doesnotexist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>

        <h4 class="modal-title" id="myModalLabel">
          <img src="{% static 'img/logo/little_owl_grey.png' %}" width="50px" alt="logo kooblit" />
          {{ title }}
        </h4>
      </div>

      <div class="modal-body">
        L'ouvrage ne dispose pas de synthèse disponible sur le site à ce jour. <br/>
        Nous allons faire notre possible  pour vous procurer une synthèse dans les plus brefs délais. <br/>
        <b>Souhaitez-vous être prévenu lorsqu'une synthèse sera en ligne?</b>
      </div>

      <div class="modal-footer">
        <button type="button" onclick="ask()" class="btn_call" data-dismiss="modal">Oui</button>
        <button type="button" class="btn_call_sec" data-dismiss="modal">Non</button>
      </div>
    </div>
  </div>
</div> <!-- Modal -->
{% endif %}
{% endblock %}
{% block script_block %}
<script type="text/javascript">
$('#myModal_doesnotexist').modal('show');
function ask(){
  $.ajax({
      url: "{% url 'book_management:ask' title %}",
      type: "GET",
      cache: false,
      success: function (data) {
        if (data !== ""){
          var pathname = window.location.pathname;
          window.location.replace("{% url 'usr_management:login' %}?next="+pathname);
        }

      },
      data: {
      }
    });
}
</script>
{% endblock %}